#ifndef LIBSME_SME_READ_ERROR_H
#define LIBSME_SME_READ_ERROR_H

enum SME_Read_Error {
    SME_READ_OK = 0,
    SME_READ_ERROR_MAGIC,
    SME_READ_ERROR_BYTE_ORDER_VERIFICATION,
    SME_READ_ERROR_VERSION_NOT_SUPPORTED,
    SME_READ_ERROR_INVALID_DATA
};

#endif /* LIBSME_SME_READ_ERROR_H */
